### ISSUE TITLE
[Data] - 코어 데이터 설계

### ISSUE THREAD

**Issue by HIBAR97** [ADA-RLD/PostKit#1]
## ✅ Todo
- [x] 코어 데이터 설계
- [x] 공용 데이터 Struct 설계
- [x] 앱 environment 연결
- [ ] Core Data PLUD
`Protocol 파일로 PLUD 안내 예정`
