### ISSUE TITLE
[Feat] - ChatGpt API 연결

### ISSUE THREAD

**Issue by whaeundo25** [ADA-RLD/PostKit#3]
## ✅ TODO
- [x] ChatGpt API  설정
- [x] ChatGpt API 연결
- [x] 각 카테고리에 맞게 프롬프트 설정
